// Real NYC Subway data for Owenz Games — Subway Driver
// Station lists are in geographic order (north → south / Queens → Brooklyn).
// t = transfers available at that station, el = elevated station, fact = fun fact shown at the stop.

export const ROUTE_COLORS = {
  '1': '#EE352E', '2': '#EE352E', '3': '#EE352E',
  '4': '#00933C', '5': '#00933C', '6': '#00933C',
  '7': '#B933AD',
  'A': '#0039A6', 'C': '#0039A6', 'E': '#0039A6',
  'B': '#FF6319', 'D': '#FF6319', 'F': '#FF6319', 'M': '#FF6319',
  'G': '#6CBE45',
  'J': '#996633', 'Z': '#996633',
  'L': '#A7A9AC',
  'N': '#FCCC0A', 'Q': '#FCCC0A', 'R': '#FCCC0A', 'W': '#FCCC0A',
  'S': '#808183',
};

// Routes whose bullets use dark text on a light background
export const DARK_TEXT_ROUTES = new Set(['N', 'Q', 'R', 'W']);

export const LINES = {
  '1': {
    id: '1',
    name: '1 Train',
    longName: 'Broadway–7 Avenue Local',
    color: '#EE352E',
    darkText: false,
    // termini[0] = north end, termini[1] = south end
    termini: ['Van Cortlandt Park–242 St', 'South Ferry'],
    dirLabels: ['Uptown', 'Downtown'],
    stations: [
      { n: 'Van Cortlandt Park–242 St', t: [], el: true, fact: 'The very top of the 1 line — right next to giant Van Cortlandt Park!' },
      { n: '238 St', t: [], el: true },
      { n: '231 St', t: [], el: true },
      { n: 'Marble Hill–225 St', t: [], el: true, fact: 'Marble Hill is the only piece of Manhattan on the mainland!' },
      { n: '215 St', t: [], el: true },
      { n: '207 St', t: [], el: true },
      { n: 'Dyckman St', t: [], el: true, fact: 'Here the 1 train dives from the sky down into the tunnel!' },
      { n: '191 St', t: [], fact: 'The deepest station in all of New York City!' },
      { n: '181 St', t: [] },
      { n: '168 St–Washington Hts', t: ['A', 'C'] },
      { n: '157 St', t: [] },
      { n: '145 St', t: [] },
      { n: '137 St–City College', t: [] },
      { n: '125 St', t: [], el: true, fact: 'Surprise! The train pops out of the tunnel onto a big bridge here.' },
      { n: '116 St–Columbia University', t: [] },
      { n: 'Cathedral Pkwy–110 St', t: [] },
      { n: '103 St', t: [] },
      { n: '96 St', t: ['2', '3'] },
      { n: '86 St', t: [] },
      { n: '79 St', t: [] },
      { n: '72 St', t: ['2', '3'] },
      { n: '66 St–Lincoln Center', t: [], fact: 'Musicians with violins and tubas ride from here to Lincoln Center.' },
      { n: '59 St–Columbus Circle', t: ['A', 'B', 'C', 'D'], fact: 'Central Park is right upstairs!' },
      { n: '50 St', t: [] },
      { n: 'Times Sq–42 St', t: ['2', '3', '7', 'N', 'Q', 'R', 'W', 'S', 'A', 'C', 'E'], fact: 'The busiest subway station in New York City!' },
      { n: '34 St–Penn Station', t: ['2', '3'], fact: 'Big Amtrak and LIRR trains live under Penn Station too!' },
      { n: '28 St', t: [] },
      { n: '23 St', t: [] },
      { n: '18 St', t: [] },
      { n: '14 St', t: ['2', '3', 'F', 'M', 'L'] },
      { n: 'Christopher St–Stonewall', t: [] },
      { n: 'Houston St', t: [] },
      { n: 'Canal St', t: [] },
      { n: 'Franklin St', t: [] },
      { n: 'Chambers St', t: ['2', '3'] },
      { n: 'WTC Cortlandt', t: ['2', '3', '4', '5', 'A', 'C', 'E', 'J', 'Z', 'R', 'W'], fact: 'Look up — the giant white Oculus building is right above!' },
      { n: 'Rector St', t: [] },
      { n: 'South Ferry', t: ['R', 'W'], fact: 'Last stop! Hop on the big orange Staten Island Ferry!' },
    ],
  },

  'R': {
    id: 'R',
    name: 'R Train',
    longName: 'Broadway Local',
    color: '#FCCC0A',
    darkText: true,
    termini: ['Forest Hills–71 Av', 'Bay Ridge–95 St'],
    dirLabels: ['To Queens', 'To Brooklyn'],
    stations: [
      { n: 'Forest Hills–71 Av', t: ['E', 'F', 'M'], fact: 'The R starts here in Queens — one of the longest local rides in NYC!' },
      { n: '67 Av', t: ['M'] },
      { n: '63 Dr–Rego Park', t: ['M'] },
      { n: 'Woodhaven Blvd', t: ['M'] },
      { n: 'Grand Av–Newtown', t: ['M'] },
      { n: 'Elmhurst Av', t: ['M'] },
      { n: 'Jackson Hts–Roosevelt Av', t: ['E', 'F', 'M', '7'], fact: 'The purple 7 train rumbles on stilts right above this station!' },
      { n: '65 St', t: ['M'] },
      { n: 'Northern Blvd', t: ['M'] },
      { n: '46 St', t: ['M'] },
      { n: 'Steinway St', t: ['M'] },
      { n: '36 St', t: ['M'] },
      { n: 'Queens Plaza', t: ['E', 'M'] },
      { n: 'Lexington Av/59 St', t: ['N', 'W', '4', '5', '6'], fact: 'Hello Manhattan! The train just zoomed under the East River.' },
      { n: '5 Av/59 St', t: ['N', 'W'], fact: 'Central Park is right upstairs!' },
      { n: '57 St–7 Av', t: ['N', 'Q', 'W'] },
      { n: '49 St', t: ['N', 'W'] },
      { n: 'Times Sq–42 St', t: ['N', 'Q', 'W', '1', '2', '3', '7', 'S', 'A', 'C', 'E'], fact: 'The busiest subway station in New York City!' },
      { n: '34 St–Herald Sq', t: ['B', 'D', 'F', 'M', 'N', 'Q', 'W'] },
      { n: '28 St', t: ['W'] },
      { n: '23 St', t: ['W'] },
      { n: '14 St–Union Sq', t: ['N', 'Q', 'W', '4', '5', '6', 'L'] },
      { n: '8 St–NYU', t: ['W'] },
      { n: 'Prince St', t: ['W'] },
      { n: 'Canal St', t: ['N', 'Q', 'W', 'J', 'Z', '6'] },
      { n: 'City Hall', t: ['W'], fact: 'The very first NYC subway opened near here in 1904!' },
      { n: 'Cortlandt St', t: ['W', '1', '2', '3', '4', '5', 'A', 'C', 'E', 'J', 'Z'] },
      { n: 'Rector St', t: ['W'] },
      { n: 'Whitehall St–South Ferry', t: ['W', '1'], fact: 'The Staten Island Ferry sails from right up there!' },
      { n: 'Court St', t: ['2', '3', '4', '5'], fact: 'Hello Brooklyn! That was another trip under the East River.' },
      { n: 'Jay St–MetroTech', t: ['A', 'C', 'F'] },
      { n: 'DeKalb Av', t: ['B', 'Q'] },
      { n: 'Atlantic Av–Barclays Ctr', t: ['2', '3', '4', '5', 'B', 'D', 'N', 'Q'], fact: 'Basketball games happen right above at Barclays Center!' },
      { n: 'Union St', t: [] },
      { n: '4 Av–9 St', t: ['F', 'G'], fact: 'The orange F train crosses way up on a viaduct above this stop.' },
      { n: 'Prospect Av', t: [] },
      { n: '25 St', t: [] },
      { n: '36 St', t: ['D', 'N'] },
      { n: '45 St', t: [] },
      { n: '53 St', t: [] },
      { n: '59 St', t: ['N'] },
      { n: 'Bay Ridge Av', t: [] },
      { n: '77 St', t: [] },
      { n: '86 St', t: [] },
      { n: 'Bay Ridge–95 St', t: [], fact: 'Last stop! The giant Verrazzano-Narrows Bridge is just down the street.' },
    ],
  },
};
